# Generated by Django 5.1.2 on 2024-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_user_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
