# Generated by Django 5.1.2 on 2024-11-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(),
        ),
    ]
